routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\ConversationController;
use App\Http\Controllers\ConversationQuestionController;
use App\Http\Controllers\FacebookBotController;
use App\Http\Controllers\FbBotController;
use App\Http\Controllers\FbPageController;
use App\Http\Controllers\FbReplayController;
use App\Http\Controllers\FbReportController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\WebChatController;

Auth::routes();
Route::get('logout', [LoginController::class, 'logout'])->name('logout');


Route::get('/chat', function(){
    return view('chat');
})->name('chat');

Route::get('/webChat',[WebChatController::class, 'index'])->name('webChat');
Route::post('/webChat',[WebChatController::class, 'index'])->name('webChat');
Route::match(['get', 'post'],'/chatBot', [FacebookBotController::class,'index'])->name('chatBot');

Route::middleware(['auth:web'])->group(function () {

    Route::get('/', [HomeController::class, 'home'])->name('home');
    Route::get('/home', [HomeController::class, 'home'])->name('home');
    // Other Routes
    Route::get('/log', [LogController::class, 'index'])->name('log.index');
    Route::get('/setting', [SettingController::class, 'index'])->name('setting.index');
    Route::post('/setting', [SettingController::class, 'store'])->name('setting.store');
    Route::get('/profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::post('/profile', [ProfileController::class, 'store'])->name('profile.store');
    
    Route::get('/fbReplay/{fbBot}/{replayButton}', [FbReplayController::class, 'create'])->name('fbReplay.create');
    Route::get('/fbReplay', [FbReplayController::class, 'index'])->name('fbReplay.index');
    Route::post('/fbReplay', [FbReplayController::class, 'store'])->name('fbReplay.store');
    Route::get('/deleteFbReplay/{fbReplay}', [FbReplayController::class, 'destroy'])->name('fbReplay.destroy');
    Route::post('/updateFbReplay', [FbReplayController::class, 'update'])->name('fbReplay.update');
    Route::get('/fbReport', [FbReportController::class, 'index'])->name('fbReport.index');
    Route::get('/postbackReprtForm', [FbReportController::class, 'postbackReprtForm'])->name('fbReport.postbackReprtForm');
    Route::post('/postbackReprtReport', [FbReportController::class, 'postbackReprtReport'])->name('fbReport.postbackReprtReport');
    Route::get('/botReprtForm', [FbReportController::class, 'botReprtForm'])->name('fbReport.botReprtForm');
    Route::post('/botReprt', [FbReportController::class, 'botReprt'])->name('fbReport.botReprt');
    Route::get('/conversationReprt', [FbReportController::class, 'conversationReprtForm'])->name('fbReport.conversationReprtForm');
    Route::post('/conversationReprt', [FbReportController::class, 'conversationReprt'])->name('fbReport.conversationReprt');
    
    // Resources
    Route::resources([
        'user' => UserController::class,
        'role' => RoleController::class,
        'fbPage' => FbPageController::class,
        'fbBot' => FbBotController::class,
        'conversation' => ConversationController::class,
        'conversationQuestion' => ConversationQuestionController::class
    ]);
    // Data Table
    Route::get('/dataTable/role', [RoleController::class, 'dataTable'])->name('dataTable.role');
    Route::get('/dataTable/user', [UserController::class, 'dataTable'])->name('dataTable.user');
    Route::get('/dataTable/log', [LogController::class, 'dataTable'])->name('dataTable.log');
    Route::get('/dataTable/fbPage', [FbPageController::class, 'dataTable'])->name('dataTable.fbPage');
    Route::get('/dataTable/fbBot', [FbBotController::class, 'dataTable'])->name('dataTable.fbBot');
    Route::get('/dataTable/conversation', [ConversationController::class, 'dataTable'])->name('dataTable.conversation');
    Route::get('/dataTable/conversationQuestion', [ConversationQuestionController::class, 'dataTable'])->name('dataTable.conversationQuestion');
    
    // Select 2
    Route::get('/select/user', [UserController::class, 'userData'])->name('select.userData');
    Route::get('/select/fbPage', [FbPageController::class, 'fbPageData'])->name('select.fbPageData');
    Route::get('/select/fbBot', [FbBotController::class, 'fbBotData'])->name('select.fbBotData');
    Route::get('/select/conversation', [ConversationController::class, 'conversationData'])->name('select.conversationData');
    Route::get('/select/fbReplay', [FbReplayController::class, 'fbReplayData'])->name('select.fbReplay');

    

});
// locale Route
Route::get('lang/{locale}', [LanguageController::class, 'swap']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use App\Helpers\ModelHelper;

class User extends Authenticatable
{
    use HasRoles,HasFactory, Notifiable, ModelHelper;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'username',
        'password',
        'user_type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    public function warehouse()
    {
        return $this->belongsToMany(Warehouse::class);
    }

    public function type()
    {
        return $this->HasMany(UserType::class);
    }
}

app/Models/UserType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserType extends Model
{
    use HasFactory;
    protected $guarded = [];
    protected $table = 'user_type';
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\DataTable;
use App\Http\Controllers\Controller;
use App\Http\Requests\User\UserStoreRequest;
use App\Http\Requests\User\UserUpdateRequest;
use App\Models\User;
use App\Services\UserService;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    use DataTable;
    public $service;

    public function __construct(UserService $service)
    {
        $this->authorizeResource(User::class);
        $this->service = $service;
    }

    public function index()
    {
        $breadcrumbs = [
            ['link'=>"home",'name'=>__('common.home')], ['name'=>__('user.users')]
        ];
        return view('user.index', ['breadcrumbs' => $breadcrumbs]);
    }

    public function create(Request $request)
    {
        //$this->authorize('create',User::class);
        $breadcrumbs = [
            ['link'=>"home",'name'=>__('common.home')], ['link'=>route('user.index'),'name'=>__('user.users')], ['name'=>__('common.add')]
        ];
        $roles = Role::all()->transform(function ($item, $key) {
            return ['title'=>$item->name,'value'=>$item->id];
        });
        $userTypes = collect($this->service->userTypes())->transform(function ($item, $key) {
            return ['title'=>$item,'value'=>$key];
        });
        return view('user.add', ['breadcrumbs' => $breadcrumbs, 'roles' => $roles,'userTypes' => $userTypes]);
    }
    
    public function store(UserStoreRequest $request)
    {
        if($this->service->create($request))
        {
            return back()->with('message', __('user.successAdd'));
        }
    }

    public function show(User $user)
    {
        //
    }

    public function edit(User $user)
    {
        $breadcrumbs = [
            ['link'=>"home",'name'=>__('common.home')], ['link'=>route('user.index'),'name'=>__('user.users')], ['name'=>__('common.edit')]
        ];
        $roles = Role::all()->transform(function ($item, $key) {
            return ['title'=>$item->name,'value'=>$item->id];
        });
        $userTypes = collect($this->service->userTypes())->transform(function ($item, $key) {
            return ['title'=>$item,'value'=>$key];
        });
        $selectedTypes = count($user->type->pluck('type_id'))>0?$user->type->pluck('type_id')->toArray():[];
        return view('user.edit', ['breadcrumbs' => $breadcrumbs,'user' => $user, 'roles' => $roles,'userTypes' => $userTypes, 'selectedTypes' => $selectedTypes]);
    }

    public function update(UserUpdateRequest $request, User $user)
    {
        if($this->service->update($request,$user))
        {
            return back()->with('message', __('user.successUpdate'));
        }
    }
    
    public function destroy(User $user)
    {
        if($this->service->delete($user))
        {
            return back()->with('message', __('user.successDelete'));
        }
    }
    
    public function userData(Request $request)
    {
        $users =$this->service->model->where('name', 'LIKE' , '%'.$request->q.'%');
        if(isset($request->user_type))
        {
            $users->where('user_type',$request->user_type);
        }
        return $users->get()->transform(function ($item, $key) {
                return ['text'=>$item->name,'id'=>$item->id];
            });
    }
}

resources/views/user/action.blade.php
<div class="dropdown">
    <button type="button" class="btn btn-sm dropdown-toggle hide-arrow waves-effect waves-float waves-light" data-toggle="dropdown" aria-expanded="false">
      <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-vertical"><circle cx="12" cy="12" r="1"></circle><circle cx="12" cy="5" r="1"></circle><circle cx="12" cy="19" r="1"></circle></svg>
    </button>
    <div class="dropdown-menu" style="">
      @can('Edit User')
        <a class="dropdown-item text-center" href="{{route('user.index')}}/`+row.id+`/edit">
          <span>{{__('common.edit')}}</span>
        </a>
      @endcan
      @can('Delete User')
        <form action="{{route('user.index')}}/`+row.id+`" method="POST">
          <input type="hidden" name="_method" value="DELETE">
          @csrf
          <button class="btn btn-flat-danger waves-effect btn-block">{{__('common.delete')}}</button>
        </form>
      @endcan
    </div>
</div>

resources/views/user/add.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', __('common.add'))
@section('content')
@if($errors->any())
<x-forms.alert title="{{__('common.error')}}" text="{!!'- '.implode('<br />- ',(array) $errors->all())!!}" type="danger" />
@endif

@if(\Session::has('message'))
<x-forms.alert title="{{__('common.success')}}" text="{{\Session::get('message')}}" type="success" />
@endif

<div class="card">
  <div class="card-body">
    <div class="card-text">
        <form method="POST" action="{{route('user.store')}}" class="form" autocomplete="off">
            @csrf
            <div class="row">
                <x-forms.inputText 
                    type="text"
                    name="name"
                    required="yes"
                    title="{{__('user.name')}}"
                        />
            
                <x-forms.inputText 
                    type="text"
                    name="username"
                    required="yes"
                    title="{{__('user.username')}}"
                        />
                
                <x-forms.inputText 
                    type="password"
                    name="password"
                    title="{{__('auth.Password')}}"
                        />
                
                <x-forms.select 
                    name="role_id"
                    title="{{__('user.role')}}"
                    :items="$roles" />
                    
                <div class="col-12">
                    <x-forms.button 
                        class="primary"
                        type="submit"
                        title="{{__('common.save')}}"
                            />
                    
                    <x-forms.button 
                        class="secondary"
                        type="reset"
                        title="{{__('common.reset')}}"
                            />
                </div>
            </div>
        </form>
    </div>
  </div>
</div>

@endsection

resources/views/user/edit.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', __('common.edit'))
@section('content')
@if($errors->any())
<x-forms.alert title="{{__('common.error')}}" text="{!!'- '.implode('<br />- ',(array) $errors->all())!!}" type="danger" />
@endif

@if(\Session::has('message'))
<x-forms.alert title="{{__('common.success')}}" text="{{\Session::get('message')}}" type="success" />
@endif

<div class="card">
  <div class="card-body">
    <div class="card-text">
        <form method="POST" action="{{route('user.update',['user'=>$user->id])}}" class="form" autocomplete="off">
            <input type="hidden" name="_method" value="PUT">
            @csrf
            <div class="row">
                <x-forms.inputText 
                    type="text"
                    name="name"
                    value="{{$user->name}}"
                    title="{{__('user.name')}}"
                        />
            
                <x-forms.inputText 
                    type="text"
                    name="username"
                    value="{{$user->username}}"
                    title="{{__('user.username')}}"
                        />
                
                <x-forms.inputText 
                    type="password"
                    name="password"
                    title="{{__('auth.Password')}}"
                        />
                
                <x-forms.select 
                    name="role_id"
                    title="{{__('user.role')}}"
                    :selected="$user->roles->pluck('name')->toArray()"
                    :items="$roles" />

                <div class="col-12">
                    <x-forms.button 
                        class="primary"
                        type="submit"
                        title="{{__('common.save')}}"
                            />
                    
                    <x-forms.button 
                        class="secondary"
                        type="reset"
                        title="{{__('common.reset')}}"
                            />
                </div>
            </div>
        </form>
    </div>
  </div>
</div>

@endsection

resources/views/user/index.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', __('user.users'))
@section('content')

@if(\Session::has('message'))
<x-forms.alert title="{{__('common.success')}}" text="{{\Session::get('message')}}" type="success" />
@endif

<div class="card">
  <div class="card-body">
    <div class="card-text">

        <x-forms.dataTable
          name="users"
          action="user.action"
          title="{{__('user.users')}}"
          :colums="[['name',__('user.name')],['username',__('user.username')],['created_at',__('common.created_at')]]"
          link="{{route('dataTable.user')}}"
          addNew="{{route('user.create')}}"
          canAdd="{{\auth::user()->can('Add User')}}"
          canEdit="{{\auth::user()->can('Edit User')}}"
          />

    </div>
  </div>
</div>

@endsection